### ISSUE TITLE
Blank import aliases when generating with hooks and a custom baseQuery

### ISSUE THREAD

**Issue by tricheco** [rtk-incubator/rtk-query-codegen#83] opened 2021-11-17 21:15 UTC
When running (roughly) this command in CI today:
```
npx @rtk-incubator/rtk-query-codegen-openapi --hooks --baseQuery infr/baseQuery.ts openapi.yml > dest.ts
```
I got this error.
```
SyntaxError: Identifier expected. (1:24)
> 1 | import { createApi as  } from "@reduxjs/toolkit/query/react";
    |                        ^
  2 | import { type customBaseQuery as  } from "infr/baseQuery";
  3 | export const api = createApi({
  4 |     baseQuery: customBaseQuery,
    at e (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/parser-typescript.js:1:322)
    at /home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/parser-typescript.js:22:3328487
    at Object.parse (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/parser-typescript.js:22:3328520)
    at Object.parse$a [as parse] (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/index.js:12513:19)
    at coreFormat (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/index.js:14044:16)
    at formatWithCursor$1 (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/index.js:14284:14)
    at /home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/index.js:59304:12
    at Object.format (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/prettier/index.js:59324:12)
    at prettify (/home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/utils/prettier.js:53:21)
    at /home/runner/.npm/_npx/3c5ed9efbe5d2091/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/bin/cli.js:92:52 {
  loc: { start: { line: 1, column: 24 } },
  codeFrame: '> 1 | import { createApi as  } from "@reduxjs/toolkit/query/react";\n' +
    '    |                        ^\n' +
    '  2 | import { type customBaseQuery as  } from "infr/baseQuery";\n' +
    '  3 | export const api = createApi({\n' +
    '  4 |     baseQuery: customBaseQuery,'
}
```
I have the same version in local, and that was working until I cleared my npx cache, after which the problem appeared there too.

PS: the problem started occurring today (using 0.5.0), and after a few successful runs in the last few days, without changing the definition.

**Comment by Meligy** [comment] 2021-11-18 01:29
This seems to happening when using [TypeScript 4.5](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/).

**Comment by Meligy** [comment] 2021-11-18 01:32
Probably caused by https://github.com/dsherret/ts-morph/issues/1221.

**Comment by pdll** [comment] 2021-11-18 09:25
Having the same issue. It's quite critical for out project, because we are relying on RTK query codegen.

**Comment by phryneas** [comment] 2021-11-18 09:28
Then please for now use the codegen from a second folder with TS 4.4 installed. I just had an eye operation and can't even see on both eyes yet, it's highly unlikely I'll be able to fix this on short terms notice.

**Comment by pdll** [comment] 2021-11-18 09:56
Didn't work for me.

**Comment by phryneas** [comment] 2021-11-18 10:17
Well, some dependency suddenly changed. Our package didn't - and I'm sorry, right now I just cannot debug this. 
You'll have to try around with different dependencies.

**Comment by pdll** [comment] 2021-11-18 13:12
Maybe someone from your team can debug this?

**Comment by ericlamb** [comment] 2021-11-18 13:27
I was able to work around this by installing the `@rtk-incubator/rtk-query-codegen-openapi` package in my React project as a dev dependency.  Then changing the paths in the build process to execute the command from the React project folder.

```
npm install --save-dev @rtk-incubator/rtk-query-codegen-openapi
```

Previously I was running the npx command from the folder with my backend code. This was causing it to use a globally installed version of TypeScript which must have automatically updated yesterday when TS 4.5 was released.

**Comment by phryneas** [comment] 2021-11-18 18:00
Could you please give me feedback if https://github.com/rtk-incubator/rtk-query-codegen/pull/84 works for you as a fix?

**Comment by Meligy** [comment] 2021-11-18 23:16
@phryneas is there a way to try it as an npm package without linking etc.? Thanks.

**Comment by phryneas** [comment] 2021-11-19 12:52
Unfortunately not - after moving to the RTK monorepo we'll have CodeSandbox package builds for each commit. Right now I'd recommend trying this with `yalc`.

**Comment by Meligy** [comment] 2021-11-19 13:12
I found another small issue, and added testing commands to the PR.

**Comment by phryneas** [comment] 2021-11-21 15:47
fixed in https://github.com/rtk-incubator/rtk-query-codegen/releases/tag/v0.5.1

**Closed by phryneas** 2021-11-21 15:47 UTC
